# Generated by Django 3.2.9 on 2022-03-18 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='bouns',
            new_name='Bonus',
        ),
    ]
